print("                                       ..")
print("                                   ..      ..")
print("                               ..              ..")
print("                           ..                      ..")
print("                       ..                              ..")
print("                   ..          __               __         ..")
print("               ..             (__)             (__)            ..")
print("           ..                                                      ..")
print("       ..                    \                     /                   ..")
print("           ..                 \___________________/                ..")
print("               ..                                              ..")
print("                   ..                                       ..")
print("                       ..                              ..")
print("                           ..                      ..")
print("                               ..              ..")
print("                                   ..      ..")
print("                                       ..")