print("              oo")
print("            oo  oo")
print("          oo      oo")
print("        oo          oo")
print("      oo              oo")
print("    oo     0       0     oo")
print("  oo                      oo")
print("    oo     |________|    oo")
print("      oo              oo")
print("        oo          oo")
print("          oo      oo")
print("            oo  oo")
print("              oo")
